server:
  port: 8000

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      routes:
        - id: auth-internal-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/internal/**
          filters:
            - AuthenticationFilter

        - id: auth-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: notification-service-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthenticationFilter

        - id: certification-service-route
          uri: lb://CERTIFICATION-SERVICE
          predicates:
            - Path=/api/certifications/**
        - id: activity-service-route
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activities/**
          filters:
            - AuthenticationFilter

        # Định tuyến Swagger API Docs từ các Service con
        - id: openapi-auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - RewritePath=/v3/api-docs/auth-service, /v3/api-docs

        - id: openapi-user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /v3/api-docs

        - id: openapi-notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/v3/api-docs/notification-service
          filters:
            - RewritePath=/v3/api-docs/notification-service, /v3/api-docs

        - id: openapi-certification
          uri: lb://CERTIFICATION-SERVICE
          predicates:
            - Path=/v3/api-docs/certification-service
          filters:
            - RewritePath=/v3/api-docs/certification-service, /v3/api-docs
        - id: openapi-activity
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/v3/api-docs/activity-service
          filters:
            - RewritePath=/v3/api-docs/activity-service, /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth-service
      - name: User Service
        url: /v3/api-docs/user-service
      - name: Notification Service
        url: /v3/api-docs/notification-service
      - name: Certification Service
        url: /v3/api-docs/certification-service
      - name: Activity Service
        url: /v3/api-docs/activity-service
